# have to use vagrant to install snap (see https://github.com/electron-userland/electron-installer-snap/issues/83)
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.synced_folder ".", "/home/vagrant/app"

  config.vm.provider "vmware_fusion" do |v|
    # Customize the amount of memory on the VM:
    v.memory = "8192"
  end

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "8192"
    vb.cpus = 4
  end
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get dist-upgrade -y
  sudo apt install -y build-essential
  # install nvm if not already
  NVM_DIR="$HOME/.nvm"
  if [ ! -d "$NVM_DIR" ]; then
  NVM_VERSION="v12.4.0"
  mkdir $HOME/.nvm
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  nvm install "$NVM_VERSION"
  fi


  # install node if not already
  if [ ! -x "$(command -v node)" ]
  then
  nvm install node
  sudo ln -s $(which npm) /usr/bin/npm
  sudo ln -s $(which node) /usr/bin/node
  fi

  # install node if not already
  if [ ! -x "$(command -v yarn)" ]
  then
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  sudo apt-get update && sudo apt-get install yarn -y --no-install-recommends
  fi
  SHELL
end
